"""
Action generator for L2P CLI.

Generates PDDL actions from descriptions.
"""

import os
import sys
import argparse
from pathlib import Path
from typing import Dict, Any, Optional, List

from ..generate import GeneratorBase
from ...utils.config import get_config_manager, CLIError
from ...utils.templates import get_template_manager
from ...utils.errors import handle_error


def add_subparser(subparsers):
    """Add action generator subparser."""
    parser = subparsers.add_parser(
        "action",
        help="Generate PDDL action",
        description="Generate a PDDL action from description.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Generate action with basic description
  l2p generate action --name "pick-up" --desc "pick up a block"
  
  # With types and predicates
  l2p generate action --name "stack" --desc "stack block on another" \\
    --types-file types.json --predicates-file predicates.json
  
  # Extract new predicates from action
  l2p generate action --name "move" --desc "move object" --extract-new-predicates
  
  # Output in different formats
  l2p generate action --name "pick-up" --desc "description" --format json --output action.json
        """,
    )
    
    # Required arguments
    parser.add_argument(
        "--name",
        type=str,
        required=True,
        help="Action name"
    )
    
    parser.add_argument(
        "--desc",
        type=str,
        required=True,
        help="Action description (text or path to file)"
    )
    
    # Optional arguments
    parser.add_argument(
        "--types-file",
        type=str,
        help="Types file (JSON/YAML) for action parameters"
    )
    
    parser.add_argument(
        "--constants-file",
        type=str,
        help="Constants file (JSON/YAML)"
    )
    
    parser.add_argument(
        "--predicates-file",
        type=str,
        help="Predicates file (JSON/YAML) for preconditions/effects"
    )
    
    parser.add_argument(
        "--functions-file",
        type=str,
        help="Functions file (JSON/YAML)"
    )
    
    parser.add_argument(
        "--action-list-file",
        type=str,
        help="File with list of other actions (JSON/YAML/text)"
    )
    
    parser.add_argument(
        "--extract-new-predicates",
        action="store_true",
        help="Extract new predicates generated by the action"
    )
    
    parser.add_argument(
        "--template-file",
        type=str,
        help="Custom template file (default: formalize_pddl_action.txt)"
    )
    
    parser.add_argument(
        "--format",
        type=str,
        choices=["pddl", "json", "yaml"],
        default="pddl",
        help="Output format (default: pddl)"
    )
    
    parser.add_argument(
        "--output", "-o",
        type=str,
        help="Output file for action (default: stdout)"
    )
    
    parser.add_argument(
        "--predicates-output",
        type=str,
        help="Output file for new predicates (if --extract-new-predicates)"
    )
    
    parser.add_argument(
        "--max-retries",
        type=int,
        default=3,
        help="Maximum retry attempts for LLM (default: 3)"
    )
    
    parser.add_argument(
        "--no-validation",
        action="store_true",
        help="Disable syntax validation"
    )
    
    parser.set_defaults(func=generate_action_command)


def generate_action_command(args):
    """Execute action generation command."""
    try:
        generator = ActionGenerator()
        generator.generate(args)
    except Exception as e:
        handle_error(e)
        sys.exit(1)


class ActionGenerator(GeneratorBase):
    """Generator for PDDL actions."""
    
    def generate(self, args):
        """Generate action based on command line arguments."""
        # Load action description
        action_desc = self._load_description(args.desc)
        
        # Load supporting files
        types = self._load_optional_file(args.types_file, "types")
        constants = self._load_optional_file(args.constants_file, "constants")
        predicates = self._load_optional_file(args.predicates_file, "predicates")
        functions = self._load_optional_file(args.functions_file, "functions")
        action_list = self._load_optional_file(args.action_list_file, "action list")
        
        # Convert predicates to Predicate objects if needed
        # NOTE: BUG
        predicate_objects = None
        if predicates:
            from l2p import Predicate
            predicate_objects = []
            if isinstance(predicates, list):
                for pred in predicates:
                    if isinstance(pred, dict) and 'name' in pred:
                        predicate_objects.append(Predicate(pred['name'], pred.get('params', [])))
                    else:
                        try:
                            predicate_objects.append(Predicate.from_string(str(pred)))
                        except:
                            predicate_objects.append(Predicate(str(pred), []))
        
        # Convert functions to Function objects if needed
        function_objects = None
        if functions:
            from l2p import Function
            function_objects = []
            if isinstance(functions, list):
                for func in functions:
                    if isinstance(func, dict) and 'name' in func:
                        function_objects.append(Function(func['name'], func.get('params', [])))
                    else:
                        try:
                            function_objects.append(Function.from_string(str(func)))
                        except:
                            function_objects.append(Function(str(func), []))
        
        # Determine template
        if args.template_file:
            template_content = self.load_input_file(args.template_file, "template")
        else:
            template_content = self.template_manager.get_template("formalize_pddl_action.txt", "domain")
        
        # Load LLM
        llm = self.load_llm()
        
        # Load DomainBuilder
        from l2p import DomainBuilder, SyntaxValidator
        
        domain_builder = DomainBuilder()
        
        # Configure syntax validator
        syntax_validator = None
        if not args.no_validation:
            syntax_validator = SyntaxValidator()
            syntax_validator.error_types = [
                "validate_header",
                "validate_duplicate_headers",
                "validate_unsupported_keywords",
                "validate_params",
                "validate_duplicate_predicates",
                "validate_types_predicates",
                "validate_format_predicates",
                "validate_usage_action"
            ]
        
        print(f"Generating action: {args.name}...")
        
        # Call generation method
        result = domain_builder.formalize_pddl_action(
            model=llm,
            domain_desc=action_desc,  # Using action_desc as domain_desc for single action
            prompt_template=template_content,
            action_name=args.name,
            action_desc=action_desc,
            action_list=action_list,
            types=types,
            constants=constants,
            predicates=predicate_objects,
            functions=function_objects,
            extract_new_preds=args.extract_new_predicates,
            syntax_validator=syntax_validator,
            max_retries=args.max_retries
        )
        
        action_result, new_predicates, llm_output, validation_info = result
        
        # Check validation results
        if validation_info and not validation_info[0]:
            print(f"⚠ Validation warning: {validation_info[1]}")
        
        # Format and output action
        if args.format == "pddl":
            from l2p.utils.pddl_format import format_action_to_string
            action_output = format_action_to_string(action_result, args.name)
        else:
            action_output = self.format_for_output(action_result, args.format)
        
        # Save action output
        self.save_output(action_output, args.output, args.format)
        
        # Handle new predicates if extracted
        if args.extract_new_predicates and new_predicates:
            print(f"\nExtracted {len(new_predicates)} new predicates:")
            
            if args.predicates_output:
                # Format predicates for output
                if args.format == "pddl":
                    from l2p.utils.pddl_format import format_predicates_to_string
                    predicates_output = format_predicates_to_string(new_predicates)
                else:
                    # Convert to serializable format
                    serializable_predicates = []
                    for pred in new_predicates:
                        if hasattr(pred, 'to_dict'):
                            serializable_predicates.append(pred.to_dict())
                        elif isinstance(pred, dict):
                            serializable_predicates.append(pred)
                        else:
                            serializable_predicates.append({"raw": str(pred)})
                    predicates_output = self.format_for_output(serializable_predicates, args.format)
                
                self.save_output(predicates_output, args.predicates_output, args.format)
            else:
                # Print to stdout
                for pred in new_predicates:
                    print(f"  • {pred}")
        
        # Show token usage
        input_tokens, output_tokens = llm.get_tokens()
        if input_tokens or output_tokens:
            print(f"Token usage: {input_tokens} input, {output_tokens} output")
        
    def _load_description(self, desc_input: str) -> str:
        """Load description from file or text."""
        desc_path = Path(desc_input)
        if desc_path.exists() and desc_path.is_file():
            try:
                return desc_path.read_text().strip()
            except Exception as e:
                raise CLIError(
                    f"Failed to read description file: {e}",
                    ["Check file permissions and encoding"]
                )
        return desc_input
    
    def _load_optional_file(self, file_path: Optional[str], description: str) -> Any:
        """Load optional file if provided."""
        if not file_path:
            return None
        return self.load_input_file(file_path, description)