"""
PDDL Problem Formalization/Generation Functions

This module defines the `ProblemBuilder` class and related utilities for constructing
PDDL problem specifications programmatically using structured Pydantic models.

Refer to: https://ai-planning.github.io/l2p/docs/l2p.html for more information
how to use class functions. Refer to l2p/templates in: https://github.com/AI-Planning/l2p
for how to structurally prompt LLMs so they are compatible with class function parsing.
"""

import time
from typing import Optional, Type, TypeVar, Union

from l2p.llm import BaseLLM, require_llm
from l2p.utils.pddl_format import *
from l2p.utils.pddl_parser import parse_xml_tags, parse_component
from l2p.utils.pddl_prompt import DEF_PROBLEM_PROMPTS, build_ctx, safe_format
from l2p.utils.pddl_types import DomainDetails, ProblemDetails

T = TypeVar("T", bound=BaseModel)


class ProblemBuilder:
    def __init__(
        self,
        problem_details: Optional[ProblemDetails] = None,
        domain_details: Optional[DomainDetails] = None,
        **kwargs,
    ) -> None:
        """
        Initializes an L2P problem builder object using Pydantic ProblemDetails root model.
        Args:
            problem_details (ProblemDetails | None): A fully validated Problem Pydantic model.
            domain_details (DomainDetails | None): A fully validated Domain Pydantic model.
            **kwargs: Optional keyword arguments to initialize ProblemDetails directly
                (e.g., name="my-problem", objects=[...], initial_state=[...], etc.).

        Refer to l2p/utils/pddl_types.py to see how the Pydantic classes are passed.
        """
        if problem_details:
            self.problem_details = problem_details
            if (
                not self.problem_details.domain_name
                or self.problem_details.domain_name == "domain-placeholder"
            ):
                if domain_details:
                    self.problem_details.domain_name = domain_details.name
        else:
            problem_name = kwargs.pop("name", "problem-placeholder")

            if "domain_name" in kwargs:
                dom_name = kwargs.pop("domain_name")
            elif domain_details:
                dom_name = domain_details.name
            else:
                dom_name = "domain-placeholder"

            self.problem_details = ProblemDetails(
                name=problem_name, domain_name=dom_name, **kwargs
            )

        self.domain_details = domain_details

    # ---------------------------------------------------------------------------
    # PDDL DOMAIN GENERATE FUNCTIONS
    # ---------------------------------------------------------------------------

    @require_llm
    def formalize_component(
        self,
        model: BaseLLM,
        component_class: Union[List[Type[T]], Type[T]],
        prompt_template: Optional[str] = None,
        description: Optional[str] = None,
        max_retries: int = 3,
        **ctx_kwargs,
    ) -> tuple[Dict[Type[BaseModel], List[BaseModel]], str]:
        """
        Formalizes L2P Problem components from natural language descriptions using an LLM.

        This method extracts structured PDDL components (e.g., PDDLObject, InitialState)
        by prompting the LLM and parsing its output into strict Pydantic models. It supports
        extracting single components or multiple components simultaneously.

        Args:
            model (LLM): LLM used to generate the components.
            component_class (List[Type[T]] | Type[T]): A single Pydantic model class, or a list of classes,
                defining the expected PDDL structures to extract.
            prompt_template (str = None): Query prompt template. If None, the method will
                attempt to auto-detect the correct default template based on the component class.
            description (str = None): Natural language description of the PDDL problem instance to guide the LLM.
            max_retries (int = 3): The maximum number of retry attempts if the LLM output is malformed.
            **ctx_kwargs: Additional context variables to inject into the prompt template
                (e.g., objects=list[PDDLObject], initial_state=list[InitialState]).
        Returns:
            results (Dict[Type[BaseModel], List[BaseModel]]): returns a dictionary mapping
                each class to its generated instances. For example:
                results = {
                    PDDLObject: [PDDLObject(...), ...],
                    InitialState: [InitialState(...), ...],
                    GoalState: [GoalState(...), ...]
                }

            llm_output (str): The raw string output generated by the LLM.
        Raises:
            ValueError: If an appropriate prompt template cannot be found, or if the LLM
                fails to output the expected XML tags.
            RuntimeError: If the extraction fails after the maximum number of retries.
        """
        # parse components
        is_multi_class = isinstance(component_class, list) and len(component_class) > 1
        classes = component_class if is_multi_class else [component_class]

        # retrieve prompt template (None retrieves default)
        if not prompt_template:
            if is_multi_class:
                raise ValueError(
                    f"[ERROR] Must provide prompt template for multiple class extraction."
                )

            # retrieve default template
            else:
                cls = classes[0]
                primary_tag = cls.tag if isinstance(cls.tag, str) else cls.tag[0]
                prompt_template = getattr(
                    DEF_PROBLEM_PROMPTS,
                    primary_tag,
                    getattr(DEF_PROBLEM_PROMPTS, cls.__name__, None),
                )

            # occurs if prompt template not provided and requested components > 1 (requires custom prompt)
            if not prompt_template:
                raise ValueError(
                    f"[ERROR] No prompt template provided and no default found for {classes}"
                )

        # inject context in placeholders
        prompt = safe_format(
            template=prompt_template,
            description=description,
            context=build_ctx(**ctx_kwargs),
        )

        # generate component
        for attempt in range(max_retries):
            try:
                model.reset_tokens()
                llm_output = model.query(prompt=prompt)
                results = {}

                # iterate over each class to extract
                for cls in classes:
                    tags = [cls.tag] if isinstance(cls.tag, str) else cls.tag

                    # iterate through provided xml tags according to provided classes
                    for t in tags:
                        if raw_blocks := parse_xml_tags(
                            llm_output=llm_output, tag_name=t
                        ):
                            results[cls] = parse_component(
                                raw_blocks=raw_blocks, model_class=cls, tag_name=t
                            )
                            break
                    else:
                        raise ValueError(
                            f"[ERROR] Missing expected XML block in LLM output. Looked for: {cls.tag}"
                        )

                return results, llm_output

            except Exception as e:
                print(
                    f"Error encountered during attempt {attempt + 1}/{max_retries}: {e}. "
                    f"\nLLM Output: \n\n{llm_output if 'llm_output' in locals() else 'None'}\n\n Retrying..."
                )
                time.sleep(2)  # add a delay before retrying

        raise RuntimeError("Max retries exceeded. Failed to extract component(s).")

    def generate_problem(self, problem_details: ProblemDetails) -> str:
        """
        Assembles all formatted components into a complete PDDL problem string.
        Args:
            problem_details (ProblemDetails): Pydantic model containing all PDDL problem components
        Returns:
            desc (str): PDDL problem in string format
        """
        desc = f"(define (problem {problem_details.name})\n"
        desc += f"   (:domain {problem_details.domain_name})\n"

        if problem_details.objects:
            objs_str = format_objects(problem_details.objects)
            desc += f"\n   (:objects \n{indent(string=objs_str, level=2)}\n   )"

        # check both standard and time facts lists inside initial state
        if (
            not problem_details.initial_state.facts
            and not problem_details.initial_state.timed_facts
        ):
            print("[WARNING]: Problem has no initial state.")
        else:
            init_str = format_initial_state(problem_details.initial_state)
            desc += f"\n\n   (:init \n{indent(string=init_str, level=2)}\n   )"

        # check the connditions list in goal state
        if not problem_details.goal_state.conditions:
            print("[WARNING]: Problem has no goals.")
        else:
            goal_str = format_goal_states(problem_details.goal_state)
            desc += f"\n\n   (:goal \n      {goal_str}\n   )"

        # check constraints
        if problem_details.constraint:
            constraints_str = format_constraints(problem_details.constraint)
            desc += f"\n\n   (:constraints \n{indent(string=constraints_str, level=2)}\n   )"

        # check metrics
        if problem_details.metric:
            metric_str = format_metric(problem_details.metric)
            desc += f"\n\n{indent(string=metric_str, level=1)}"

        desc += "\n)"
        desc = desc.replace("AND", "and").replace("OR", "or")
        return desc

    # ---------------------------------------------------------------------------
    # PDDL PROBLEM SET FUNCTIONS
    # ---------------------------------------------------------------------------

    SINGULAR_FIELDS = {"initial_state", "goal_state", "metric"}

    def _set_component(
        self, field_name: str, component: Union[list[T], T, None], append: bool = False
    ):
        """
        Helper method to assign or append an L2P PDDL component to the problem_details model.
        Args:
            field_name (str): The exact attribute name on the ProblemDetails Pydantic model
                (e.g., "objects", "initial_state", "goal_state").
            component (Union[list[T], T, None]): The Pydantic model instance(s) to add.
                Can be a single instance, a list of instances, or None.
            append (bool, optional): If True, concatenates the new items to the existing
                attribute list. If False, overwrites the attribute entirely. Defaults to False.
        """
        if component is None:
            if field_name in self.SINGULAR_FIELDS:
                null_default = (
                    InitialState()
                    if field_name == "initial_state"
                    else GoalState() if field_name == "goal_state" else None
                )
                setattr(self.problem_details, field_name, null_default)
                return
            else:
                setattr(self.problem_details, field_name, [])
                return

        if field_name in self.SINGULAR_FIELDS:
            setattr(self.problem_details, field_name, component)
            return

        if not isinstance(component, list):
            normalized_list = [component]
        else:
            normalized_list = component
        clean_list = [item for item in normalized_list if item is not None]

        if append:
            existing_list = getattr(self.problem_details, field_name, [])
            updated_list = existing_list + clean_list
        else:
            updated_list = clean_list
        setattr(self.problem_details, field_name, updated_list)

    def set_problem_name(self, problem_name: str = None):
        """
        Sets PDDL problem name for current specification
        Args:
            problem_name (str = None): Name for problem instance.
        """
        if problem_name:
            self.problem_details.name = problem_name
        else:
            self.problem_details.name = "problem-placeholder"

    def set_problem_desc(self, description: str = None):
        """
        Sets PDDL problem description for current specification
        Args:
            description (str = None): Description for problem instance.
        """
        if description:
            self.problem_details.desc = description
        else:
            return

    def set_objects(
        self, objects: list[PDDLObject] | PDDLObject | None, append: bool = False
    ):
        """
        Sets or appends PDDL problem objects for current specification
        Args:
            objects (list[PDDLObject] | PDDLObject | None): A single PDDLObject object,
                a list of PDDLObject objects, or None to clear the list.
            append (bool, optional): If True, appends the given types to the
                existing list. If False, overwrites the existing list completely.
                Defaults to False.
        """
        self._set_component("objects", objects, append=append)

    def set_initial_states(
        self, initial_states: InitialState | None, append: bool = False
    ):
        """
        Sets or appends PDDL problem initial states for current specification
        Args:
            initial_states (InitialState | None): A single InitialState object,
                or None to clear the list.
            append (bool, optional): If True, appends the given types to the
                existing list. If False, overwrites the existing list completely.
                Defaults to False.
        """
        self._set_component("initial_state", initial_states, append=append)

    def set_goal_states(self, goal_states: GoalState | None, append: bool = False):
        """
        Sets or appends PDDL problem goal states for current specification
        Args:
            goal_states (GoalState | None): A single GoalState object,
                or None to clear the list.
            append (bool, optional): If True, appends the given types to the
                existing list. If False, overwrites the existing list completely.
                Defaults to False.
        """
        self._set_component("goal_state", goal_states, append=append)

    def set_constraints(
        self, constraints: list[Constraint] | Constraint | None, append: bool = False
    ):
        """
        Sets or appends PDDL problem constraints for current specification
        Args:
            constraints (list[Constraint] | Constraint | None): A single Constraint object,
                a list of Constraint objects, or None to clear the list.
            append (bool, optional): If True, appends the given types to the
                existing list. If False, overwrites the existing list completely.
                Defaults to False.
        """
        self._set_component("constraint", constraints, append=append)

    def set_metric(self, metric: Metric | None, append: bool = False):
        """
        Sets or appends PDDL problem metric for current specification
        Args:
            metric (Metric | None): A single Metric object,
                or None to clear the list.
            append (bool, optional): If True, appends the given types to the
                existing list. If False, overwrites the existing list completely.
                Defaults to False.
        """
        self._set_component("metric", metric, append=append)